# Generated by Django 5.2.1 on 2025-07-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pet_description_pet_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='chip_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de chip'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_sterilized',
            field=models.BooleanField(default=False, verbose_name='Esterilizado/a'),
        ),
    ]
