# Generated by Django 5.2.1 on 2025-07-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pet_chip_number_pet_is_sterilized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='is_sterilized',
            field=models.BooleanField(blank=True, null=True, verbose_name='Esterilizado/a'),
        ),
    ]
