# Generated by Django 5.2.1 on 2025-07-19 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pet_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=255, verbose_name='Nombre de la vacuna')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('applied', 'Aplicada'), ('overdue', 'Vencida'), ('scheduled', 'Programada')], default='pending', max_length=20, verbose_name='Estado')),
                ('applied_date', models.DateField(blank=True, null=True, verbose_name='Fecha de aplicación')),
                ('next_dose_date', models.DateField(blank=True, null=True, verbose_name='Próxima dosis')),
                ('veterinarian', models.CharField(blank=True, max_length=255, null=True, verbose_name='Veterinario')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='core.pet')),
            ],
            options={
                'verbose_name': 'Vacuna de Mascota',
                'verbose_name_plural': 'Vacunas de Mascotas',
                'ordering': ['-applied_date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
