# Generated by Django 5.2.1 on 2025-07-19 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_vaccine_to_petvaccine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('upcoming', 'Próxima vacuna'), ('overdue', 'Vacuna vencida'), ('scheduled', 'Vacuna programada')], max_length=20, verbose_name='Tipo de recordatorio')),
                ('reminder_date', models.DateTimeField(verbose_name='Fecha del recordatorio')),
                ('notification_method', models.CharField(choices=[('email', 'Correo electrónico'), ('push', 'Notificación push'), ('sms', 'SMS')], default='email', max_length=10, verbose_name='Método de notificación')),
                ('days_before', models.IntegerField(default=7, verbose_name='Días de anticipación')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Enviado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensaje personalizado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet_vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.petvaccine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recordatorio de Vacuna',
                'verbose_name_plural': 'Recordatorios de Vacunas',
                'ordering': ['reminder_date', '-created_at'],
                'unique_together': {('pet_vaccine', 'user', 'reminder_type', 'days_before')},
            },
        ),
    ]
