# Generated by Django 5.2.1 on 2025-07-19 00:58

from django.db import migrations
from django.utils import timezone
from datetime import timedelta


def fix_null_reminder_dates(apps, schema_editor):
    """Fix existing VaccineReminder records with null reminder_date"""
    VaccineReminder = apps.get_model('core', 'VaccineReminder')
    
    # Eliminar recordatorios con reminder_date null
    # Es más seguro recrearlos que intentar arreglar datos inconsistentes
    null_reminders = VaccineReminder.objects.filter(reminder_date__isnull=True)
    count_deleted = null_reminders.count()
    null_reminders.delete()
    
    print(f"Deleted {count_deleted} reminders with null reminder_date")


def reverse_fix_null_reminder_dates(apps, schema_editor):
    """No reverse action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_vaccine_reminders'),
    ]

    operations = [
        migrations.RunPython(fix_null_reminder_dates, reverse_fix_null_reminder_dates),
    ]
