# Generated by Django 5.2.1 on 2026-02-11 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_country_userprofile_is_premium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='owners',
        ),
        migrations.AddField(
            model_name='pet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Dueño/a'), ('editor', 'Editor/a'), ('viewer', 'Visor/a')], default='owner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relationships', to='core.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relación Mascota-Usuario',
                'verbose_name_plural': 'Relaciones Mascota-Usuario',
                'unique_together': {('pet', 'user')},
            },
        ),
    ]
