# Generated by Django 5.2.1 on 2026-02-11 00:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pet_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='core.pet')),
            ],
            options={
                'verbose_name': 'Peso de Mascota',
                'verbose_name_plural': 'Pesos de Mascotas',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
